// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3HYct8DbTQPDQrOI1k2aMnirty7C2Gmw',
    appId: '1:629053169089:web:81323d6b525dbfd727e340',
    messagingSenderId: '629053169089',
    projectId: 'hepatodiagnosis',
    authDomain: 'hepatodiagnosis.firebaseapp.com',
    storageBucket: 'hepatodiagnosis.firebasestorage.app',
    measurementId: 'G-5ZXBGBLT4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO3nE5G48QTnq5-BGReaVsFE_RjpVDg6o',
    appId: '1:629053169089:android:0f528e9ed64134a227e340',
    messagingSenderId: '629053169089',
    projectId: 'hepatodiagnosis',
    storageBucket: 'hepatodiagnosis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ7DAEY7WZgO4eHEpQTDs04-L24v2iXJ8',
    appId: '1:629053169089:ios:eca25f85dd6ab22b27e340',
    messagingSenderId: '629053169089',
    projectId: 'hepatodiagnosis',
    storageBucket: 'hepatodiagnosis.firebasestorage.app',
    iosBundleId: 'com.example.hepatoDiagnosis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ7DAEY7WZgO4eHEpQTDs04-L24v2iXJ8',
    appId: '1:629053169089:ios:eca25f85dd6ab22b27e340',
    messagingSenderId: '629053169089',
    projectId: 'hepatodiagnosis',
    storageBucket: 'hepatodiagnosis.firebasestorage.app',
    iosBundleId: 'com.example.hepatoDiagnosis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3HYct8DbTQPDQrOI1k2aMnirty7C2Gmw',
    appId: '1:629053169089:web:725febd7e3f2265827e340',
    messagingSenderId: '629053169089',
    projectId: 'hepatodiagnosis',
    authDomain: 'hepatodiagnosis.firebaseapp.com',
    storageBucket: 'hepatodiagnosis.firebasestorage.app',
    measurementId: 'G-VJWTQWVV0H',
  );
}
